name: Economy
version: '0.0.1'
main: me.jeremiah.economy.EconomyPlugin
loader: me.jeremiah.economy.EconomyPluginLoader
api-version: '1.21'
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true