name: Economy
version: @version@
main: me.jeremiah.economy.EconomyPlugin
loader: me.jeremiah.economy.EconomyPluginLoader
api-version: '1.21'
load: STARTUP
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true